### ISSUE TITLE
Gridcoin node won't update

### ISSUE THREAD

**Issue by Jonathan43551** [stefancertic/GridCoin-Android-Wallet#2]
Hello, my app has been stuck a few thousand blocks behind with this status for days. 

Sync Status 
Net: 1461508 Node: 1424047 
37461 blocks behind.

**Comment by stefancertic** [comment]
Hello Jonathan43551,

A bug has been found and I did an update that should get the client in sync within few hours. Still I'll leave the issue open until confirmation.

Best Regards,
Stefan

**Comment by stefancertic** [comment]
According to my observations, issue has been fixed.

**Comment by Jonathan43551** [comment]
Thank you, my client is in sync now. 😀
